# netlify.toml

[build]
  # Directory to change to before starting a build
  # This is where we will look for package.json/.nvmrc/etc
  base = "/"
  
  # Directory that contains the deploy-ready HTML files and assets
  # This defaults to "dist" for Vite projects
  publish = "dist"
  
  # Default build command
  command = "npm run build"

# Redirects for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cache settings for better performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache assets with a long lifetime
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
